### ISSUE TITLE
need a wiki entry for pushing to repo

### ISSUE THREAD

**Issue by samh06** [ShalomSTEM/TaribelangProject#25]
since u cant push to main there'll need to be a wiki entry on branching and making a PR to push it to main

**Comment by samh06** [comment]
https://github.com/ShalomSTEM/TaribelangProject/wiki/Pushing-items-to-the-TaribelangProject-main-branch

**Comment by samh06** [comment]
ill fill this out p3 i think

**Comment by Charl1e-D** [comment]
I thought this was the how to contribute section of the readme

**Comment by samh06** [comment]
more detailed than the readme

**Comment by Charl1e-D** [comment]
Done

**Comment by srcoggin** [comment]
hi
