### ISSUE TITLE
need to update WIKI with github desktop instructions

### ISSUE THREAD

**Issue by samh06** [ShalomSTEM/TaribelangProject#47]

**Comment by samh06** [comment]
ill do this p4 after drawing the level design sketches I think

**Comment by srcoggin** [comment]
dont assigne me cuz i dont know what im doing on github desktop

**Comment by srcoggin** [comment]
get robert in here he will do it

**Comment by samh06** [comment]
ill do it tonight and send an email out Monday morning asking for the last 6 or 7 people and the wiki link

**Comment by samh06** [comment]
email friday this week or monday

**Comment by srcoggin** [comment]
sooooo about that wiki. do we need to get blue microbe on it??

**Comment by srcoggin** [comment]
i got u cuz

**Comment by srcoggin** [comment]
shots

**Comment by samh06** [comment]
done. sending out email soon

**Comment by samh06** [comment]
going to send email monday morning
