### ISSUE TITLE
fix branch perms

### ISSUE THREAD

**Issue by samh06** [ShalomSTEM/TaribelangProject#8]
i need to fix perms so that no one can push to main branch, this will make it so that everyone is forced to make a new branch and a PR before doing anything

**Comment by samh06** [comment]
> i need to fix perms so that no one can push to main branch, this will make it so that everyone is forced to make a new branch and a PR before doing anything

makes it so that no one pushes any broken commits to main

**Comment by Charl1e-D** [comment]
Think you can just add a new branch protection rule

**Comment by samh06** [comment]
i do, it isnt working rn

**Comment by samh06** [comment]
> Think you can just add a new branch protection rule

I just realised that your edit to the readme.md was from a PR, are you not able to push straight to main?

**Comment by samh06** [comment]
just realised it is working, thought it wasn't.

closing issue with this comment

**Comment by samh06** [comment]
+ changed it so that administrators also have to make branches before pushing
